name: push-to-lightsail

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Lightsail on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Set SSH file
        run: 'echo "SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_PK}}
        
      - name: SSH into remote
        run: |
          ssh -i key ${{secrets.USERNAME}}@${{secrets.HOST_ADDRESS}}
          cd dub-dynasty
          git pull
        
#       - name: Checkout the files
#         uses: actions/checkout@v2

#       - name: Deploy to server
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{secrets.SSH_PK}}
#           REMOTE_HOST: ${{secrets.HOST_ADDRESS}}
#           REMOTE_USER: ${{secrets.SSH_PK}}
#           TARGET: ${{secrets.TARGET_DIR}}
